name: 'FA20 Datalog Analyzer'
description: 'Analyze Subaru FA20DIT datalogs from Atlas tuning software'
author: 'AtlasDocs'

branding:
  icon: 'activity'
  color: 'blue'

inputs:
  datalog-path:
    description: 'Path to the datalog CSV file to analyze'
    required: true
  fail-on-critical:
    description: 'Fail the action if critical issues are found'
    required: false
    default: 'false'
  fail-on-high:
    description: 'Fail the action if high priority issues are found'
    required: false
    default: 'false'

outputs:
  exit-code:
    description: 'Exit code (0=ok, 1=high issues, 2=critical issues)'
    value: ${{ steps.analyze.outputs.exit_code }}
  report-path:
    description: 'Path to the JSON analysis report'
    value: ${{ steps.analyze.outputs.report_path }}
  issues-found:
    description: 'Number of issues found'
    value: ${{ steps.analyze.outputs.issues_count }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: pip install pandas

    - name: Run Analysis
      id: analyze
      shell: bash
      run: |
        python ${{ github.action_path }}/bin/fa20amp-analyze "${{ inputs.datalog-path }}" | tee output.txt
        EXIT_CODE=${PIPESTATUS[0]}
        
        echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
        
        # Get report path
        REPORT="${{ inputs.datalog-path }}"
        REPORT="${REPORT%.csv}_analysis.json"
        echo "report_path=$REPORT" >> $GITHUB_OUTPUT
        
        # Count issues
        if [ -f "$REPORT" ]; then
          ISSUES=$(python -c "import json; print(len(json.load(open('$REPORT'))['issues']))")
          echo "issues_count=$ISSUES" >> $GITHUB_OUTPUT
        fi

    - name: Check failure conditions
      shell: bash
      run: |
        EXIT_CODE=${{ steps.analyze.outputs.exit_code }}
        
        if [ "${{ inputs.fail-on-critical }}" = "true" ] && [ "$EXIT_CODE" = "2" ]; then
          echo "::error::Critical issues found in datalog"
          exit 1
        fi
        
        if [ "${{ inputs.fail-on-high }}" = "true" ] && [ "$EXIT_CODE" -ge "1" ]; then
          echo "::error::High priority issues found in datalog"
          exit 1
        fi
