#!/bin/bash
#
# DAMGood Installation Script
# Installs dependencies and creates the 'damgood' CLI command
#
# Usage: ./install.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="/usr/local/bin"

echo ""
echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                         DAMGood INSTALLER                                    ║"
echo "║                    FA20 Datalog Analyzer for WRX                             ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""

# Check for Python 3
if ! command -v python3 &> /dev/null; then
    echo "❌ Python 3 is required but not installed."
    echo "   Install with: brew install python3"
    exit 1
fi

PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2 | cut -d'.' -f1,2)
echo "✓ Found Python $PYTHON_VERSION"

# Create virtual environment if it doesn't exist
if [ ! -d "$SCRIPT_DIR/.venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$SCRIPT_DIR/.venv"
    echo "✓ Virtual environment created"
fi

# Activate and install dependencies
echo "Installing dependencies..."
"$SCRIPT_DIR/.venv/bin/pip" install --quiet --upgrade pip
"$SCRIPT_DIR/.venv/bin/pip" install --quiet -r "$SCRIPT_DIR/requirements.txt"
echo "✓ Dependencies installed"

# Create the launcher script
LAUNCHER_SCRIPT="$SCRIPT_DIR/bin/damgood"
mkdir -p "$SCRIPT_DIR/bin"

cat > "$LAUNCHER_SCRIPT" << EOF
#!/bin/bash
# DAMGood CLI Launcher
# Auto-generated by install.sh

DAMGOOD_DIR="$SCRIPT_DIR"

# Activate virtual environment and run TUI
exec "\$DAMGOOD_DIR/.venv/bin/python" "\$DAMGOOD_DIR/scripts/tui.py" "\$@"
EOF

chmod +x "$LAUNCHER_SCRIPT"
echo "✓ Launcher script created"

# Try to create symlink in /usr/local/bin
echo ""
echo "Creating 'damgood' command..."

if [ -w "$INSTALL_DIR" ]; then
    # User has write access
    ln -sf "$LAUNCHER_SCRIPT" "$INSTALL_DIR/damgood"
    echo "✓ Symlink created at $INSTALL_DIR/damgood"
else
    # Need sudo
    echo "  Creating symlink requires admin privileges..."
    if sudo ln -sf "$LAUNCHER_SCRIPT" "$INSTALL_DIR/damgood" 2>/dev/null; then
        echo "✓ Symlink created at $INSTALL_DIR/damgood"
    else
        echo "⚠️  Could not create symlink in $INSTALL_DIR"
        echo ""
        echo "To add 'damgood' to your PATH manually, add this to your shell config:"
        echo ""
        echo "  export PATH=\"$SCRIPT_DIR/bin:\$PATH\""
        echo ""
        echo "Or run directly with:"
        echo "  $LAUNCHER_SCRIPT"
    fi
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════════════════════╗"
echo "║                       INSTALLATION COMPLETE                                  ║"
echo "╚══════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Run DAMGood with:"
echo "  damgood"
echo ""
echo "Or start directly with:"
echo "  python $SCRIPT_DIR/scripts/tui.py"
echo ""
